export type UserRole = 'school_admin' | 'donor' | 'volunteer' | 'admin';

export type SchoolType = 'Blind' | 'Deaf' | 'Rural';

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type RequestCategory = 'Education Materials' | 'Infrastructure' | 'Technology' | 'Volunteer Teaching' | 'Special Equipment' | 'Food & Nutrition' | 'Healthcare' | 'Other';
export type RequestType = 'money' | 'goods' | 'volunteer';
export type Urgency = 'Low' | 'Medium' | 'High' | 'Critical';
export type RequestStatus = 'Open' | 'In Progress' | 'Fulfilled' | 'Closed' | 'Cancelled';
export type ResponseType = 'interested' | 'committed' | 'withdrawn';
export type ResponseStatus = 'Pending' | 'Accepted' | 'Rejected' | 'Completed';
export type DonationType = 'money' | 'goods';
export type PaymentMethod = 'credit_card' | 'debit_card' | 'bank_transfer' | 'paypal' | 'stripe' | 'cash';
export type PaymentStatus = 'Pending' | 'Processing' | 'Completed' | 'Failed' | 'Refunded';
export type DonationStatus = 'Pending' | 'Confirmed' | 'In Transit' | 'Delivered' | 'Cancelled';
export type SessionType = 'In-Person' | 'Virtual' | 'Hybrid';
export type SessionStatus = 'Proposed' | 'Approved' | 'Confirmed' | 'In Progress' | 'Completed' | 'Cancelled' | 'Rescheduled';
export type AttendanceStatus = 'Registered' | 'Attended' | 'Absent' | 'Late';
export type ConversationType = 'direct' | 'group' | 'request' | 'session';
export type MessageType = 'text' | 'image' | 'file' | 'system';
export type NotificationType = 'request' | 'donation' | 'session' | 'message' | 'rating' | 'system' | 'reminder';
export type NotificationPriority = 'low' | 'normal' | 'high' | 'urgent';
export type RatingType = 'session' | 'donation' | 'volunteer' | 'school' | 'donor';

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          first_name: string;
          last_name: string;
          role: UserRole;
          phone: string | null;
          address: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          first_name: string;
          last_name: string;
          role: UserRole;
          phone?: string | null;
          address?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          first_name?: string;
          last_name?: string;
          role?: UserRole;
          phone?: string | null;
          address?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      schools: {
        Row: {
          school_id: string;
          user_id: string;
          name: string;
          type: SchoolType;
          address: string;
          contact_person: string;
          phone: string | null;
          email: string | null;
          verified: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          school_id?: string;
          user_id: string;
          name: string;
          type: SchoolType;
          address: string;
          contact_person: string;
          phone?: string | null;
          email?: string | null;
          verified?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          school_id?: string;
          user_id?: string;
          name?: string;
          type?: SchoolType;
          address?: string;
          contact_person?: string;
          phone?: string | null;
          email?: string | null;
          verified?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      requests: {
        Row: {
          request_id: string;
          school_id: string;
          title: string;
          description: string;
          category: RequestCategory;
          type: RequestType;
          urgency: Urgency;
          status: RequestStatus;
          target_amount: number | null;
          raised_amount: number;
          required_items: Json | null;
          required_volunteers: number | null;
          volunteers_responded: number;
          students_impacted: number | null;
          deadline_date: string | null;
          image_url: string | null;
          location: string | null;
          priority_score: number;
          created_at: string;
          updated_at: string;
          fulfilled_at: string | null;
        };
        Insert: {
          request_id?: string;
          school_id: string;
          title: string;
          description: string;
          category: RequestCategory;
          type: RequestType;
          urgency: Urgency;
          status?: RequestStatus;
          target_amount?: number | null;
          raised_amount?: number;
          required_items?: Json | null;
          required_volunteers?: number | null;
          volunteers_responded?: number;
          students_impacted?: number | null;
          deadline_date?: string | null;
          image_url?: string | null;
          location?: string | null;
          priority_score?: number;
          created_at?: string;
          updated_at?: string;
          fulfilled_at?: string | null;
        };
        Update: {
          request_id?: string;
          school_id?: string;
          title?: string;
          description?: string;
          category?: RequestCategory;
          type?: RequestType;
          urgency?: Urgency;
          status?: RequestStatus;
          target_amount?: number | null;
          raised_amount?: number;
          required_items?: Json | null;
          required_volunteers?: number | null;
          volunteers_responded?: number;
          students_impacted?: number | null;
          deadline_date?: string | null;
          image_url?: string | null;
          location?: string | null;
          priority_score?: number;
          created_at?: string;
          updated_at?: string;
          fulfilled_at?: string | null;
        };
      };
      request_responses: {
        Row: {
          response_id: string;
          request_id: string;
          user_id: string;
          response_type: ResponseType;
          message: string | null;
          offered_amount: number | null;
          offered_items: Json | null;
          availability_dates: Json | null;
          status: ResponseStatus;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          response_id?: string;
          request_id: string;
          user_id: string;
          response_type: ResponseType;
          message?: string | null;
          offered_amount?: number | null;
          offered_items?: Json | null;
          availability_dates?: Json | null;
          status?: ResponseStatus;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          response_id?: string;
          request_id?: string;
          user_id?: string;
          response_type?: ResponseType;
          message?: string | null;
          offered_amount?: number | null;
          offered_items?: Json | null;
          availability_dates?: Json | null;
          status?: ResponseStatus;
          created_at?: string;
          updated_at?: string;
        };
      };
      donations: {
        Row: {
          donation_id: string;
          donor_id: string;
          request_id: string | null;
          school_id: string;
          donation_type: DonationType;
          amount: number | null;
          items_donated: Json | null;
          payment_method: PaymentMethod | null;
          payment_status: PaymentStatus;
          transaction_id: string | null;
          status: DonationStatus;
          tracking_number: string | null;
          delivery_date: string | null;
          is_anonymous: boolean;
          is_recurring: boolean;
          recurring_frequency: string | null;
          tax_receipt_url: string | null;
          message_to_school: string | null;
          created_at: string;
          updated_at: string;
          delivered_at: string | null;
        };
        Insert: {
          donation_id?: string;
          donor_id: string;
          request_id?: string | null;
          school_id: string;
          donation_type: DonationType;
          amount?: number | null;
          items_donated?: Json | null;
          payment_method?: PaymentMethod | null;
          payment_status?: PaymentStatus;
          transaction_id?: string | null;
          status?: DonationStatus;
          tracking_number?: string | null;
          delivery_date?: string | null;
          is_anonymous?: boolean;
          is_recurring?: boolean;
          recurring_frequency?: string | null;
          tax_receipt_url?: string | null;
          message_to_school?: string | null;
          created_at?: string;
          updated_at?: string;
          delivered_at?: string | null;
        };
        Update: {
          donation_id?: string;
          donor_id?: string;
          request_id?: string | null;
          school_id?: string;
          donation_type?: DonationType;
          amount?: number | null;
          items_donated?: Json | null;
          payment_method?: PaymentMethod | null;
          payment_status?: PaymentStatus;
          transaction_id?: string | null;
          status?: DonationStatus;
          tracking_number?: string | null;
          delivery_date?: string | null;
          is_anonymous?: boolean;
          is_recurring?: boolean;
          recurring_frequency?: string | null;
          tax_receipt_url?: string | null;
          message_to_school?: string | null;
          created_at?: string;
          updated_at?: string;
          delivered_at?: string | null;
        };
      };
      volunteer_sessions: {
        Row: {
          session_id: string;
          volunteer_id: string;
          school_id: string;
          request_id: string | null;
          title: string;
          description: string;
          subject: string;
          topic: string | null;
          session_date: string;
          start_time: string;
          end_time: string;
          duration_hours: number | null;
          location: string | null;
          session_type: SessionType;
          meeting_link: string | null;
          max_students: number | null;
          registered_students: number;
          status: SessionStatus;
          materials_needed: string[] | null;
          notes: string | null;
          is_recurring: boolean;
          recurring_pattern: string | null;
          created_at: string;
          updated_at: string;
          completed_at: string | null;
        };
        Insert: {
          session_id?: string;
          volunteer_id: string;
          school_id: string;
          request_id?: string | null;
          title: string;
          description: string;
          subject: string;
          topic?: string | null;
          session_date: string;
          start_time: string;
          end_time: string;
          duration_hours?: number | null;
          location?: string | null;
          session_type: SessionType;
          meeting_link?: string | null;
          max_students?: number | null;
          registered_students?: number;
          status?: SessionStatus;
          materials_needed?: string[] | null;
          notes?: string | null;
          is_recurring?: boolean;
          recurring_pattern?: string | null;
          created_at?: string;
          updated_at?: string;
          completed_at?: string | null;
        };
        Update: {
          session_id?: string;
          volunteer_id?: string;
          school_id?: string;
          request_id?: string | null;
          title?: string;
          description?: string;
          subject?: string;
          topic?: string | null;
          session_date?: string;
          start_time?: string;
          end_time?: string;
          duration_hours?: number | null;
          location?: string | null;
          session_type?: SessionType;
          meeting_link?: string | null;
          max_students?: number | null;
          registered_students?: number;
          status?: SessionStatus;
          materials_needed?: string[] | null;
          notes?: string | null;
          is_recurring?: boolean;
          recurring_pattern?: string | null;
          created_at?: string;
          updated_at?: string;
          completed_at?: string | null;
        };
      };
      session_participants: {
        Row: {
          participant_id: string;
          session_id: string;
          student_name: string | null;
          attendance_status: AttendanceStatus | null;
          feedback: string | null;
          created_at: string;
        };
        Insert: {
          participant_id?: string;
          session_id: string;
          student_name?: string | null;
          attendance_status?: AttendanceStatus | null;
          feedback?: string | null;
          created_at?: string;
        };
        Update: {
          participant_id?: string;
          session_id?: string;
          student_name?: string | null;
          attendance_status?: AttendanceStatus | null;
          feedback?: string | null;
          created_at?: string;
        };
      };
      conversations: {
        Row: {
          conversation_id: string;
          title: string | null;
          conversation_type: ConversationType;
          related_request_id: string | null;
          related_session_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          conversation_id?: string;
          title?: string | null;
          conversation_type: ConversationType;
          related_request_id?: string | null;
          related_session_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          conversation_id?: string;
          title?: string | null;
          conversation_type?: ConversationType;
          related_request_id?: string | null;
          related_session_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      conversation_participants: {
        Row: {
          participant_id: string;
          conversation_id: string;
          user_id: string;
          joined_at: string;
          last_read_at: string | null;
        };
        Insert: {
          participant_id?: string;
          conversation_id: string;
          user_id: string;
          joined_at?: string;
          last_read_at?: string | null;
        };
        Update: {
          participant_id?: string;
          conversation_id?: string;
          user_id?: string;
          joined_at?: string;
          last_read_at?: string | null;
        };
      };
      messages: {
        Row: {
          message_id: string;
          conversation_id: string;
          sender_id: string;
          content: string;
          message_type: MessageType;
          attachment_url: string | null;
          attachment_name: string | null;
          attachment_size: number | null;
          is_edited: boolean;
          edited_at: string | null;
          is_deleted: boolean;
          deleted_at: string | null;
          created_at: string;
        };
        Insert: {
          message_id?: string;
          conversation_id: string;
          sender_id: string;
          content: string;
          message_type?: MessageType;
          attachment_url?: string | null;
          attachment_name?: string | null;
          attachment_size?: number | null;
          is_edited?: boolean;
          edited_at?: string | null;
          is_deleted?: boolean;
          deleted_at?: string | null;
          created_at?: string;
        };
        Update: {
          message_id?: string;
          conversation_id?: string;
          sender_id?: string;
          content?: string;
          message_type?: MessageType;
          attachment_url?: string | null;
          attachment_name?: string | null;
          attachment_size?: number | null;
          is_edited?: boolean;
          edited_at?: string | null;
          is_deleted?: boolean;
          deleted_at?: string | null;
          created_at?: string;
        };
      };
      notifications: {
        Row: {
          notification_id: string;
          user_id: string;
          title: string;
          content: string;
          notification_type: NotificationType;
          related_id: string | null;
          action_url: string | null;
          is_read: boolean;
          read_at: string | null;
          priority: NotificationPriority;
          created_at: string;
        };
        Insert: {
          notification_id?: string;
          user_id: string;
          title: string;
          content: string;
          notification_type: NotificationType;
          related_id?: string | null;
          action_url?: string | null;
          is_read?: boolean;
          read_at?: string | null;
          priority?: NotificationPriority;
          created_at?: string;
        };
        Update: {
          notification_id?: string;
          user_id?: string;
          title?: string;
          content?: string;
          notification_type?: NotificationType;
          related_id?: string | null;
          action_url?: string | null;
          is_read?: boolean;
          read_at?: string | null;
          priority?: NotificationPriority;
          created_at?: string;
        };
      };
      ratings: {
        Row: {
          rating_id: string;
          rater_id: string;
          ratee_id: string;
          related_session_id: string | null;
          related_donation_id: string | null;
          rating_type: RatingType;
          rating: number;
          title: string | null;
          comment: string | null;
          feedback_categories: string[] | null;
          is_anonymous: boolean;
          is_verified: boolean;
          helpful_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          rating_id?: string;
          rater_id: string;
          ratee_id: string;
          related_session_id?: string | null;
          related_donation_id?: string | null;
          rating_type: RatingType;
          rating: number;
          title?: string | null;
          comment?: string | null;
          feedback_categories?: string[] | null;
          is_anonymous?: boolean;
          is_verified?: boolean;
          helpful_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          rating_id?: string;
          rater_id?: string;
          ratee_id?: string;
          related_session_id?: string | null;
          related_donation_id?: string | null;
          rating_type?: RatingType;
          rating?: number;
          title?: string | null;
          comment?: string | null;
          feedback_categories?: string[] | null;
          is_anonymous?: boolean;
          is_verified?: boolean;
          helpful_count?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}

export type Profile = Database['public']['Tables']['profiles']['Row'];
export type School = Database['public']['Tables']['schools']['Row'];
export type Request = Database['public']['Tables']['requests']['Row'];
export type RequestResponse = Database['public']['Tables']['request_responses']['Row'];
export type Donation = Database['public']['Tables']['donations']['Row'];
export type VolunteerSession = Database['public']['Tables']['volunteer_sessions']['Row'];
export type SessionParticipant = Database['public']['Tables']['session_participants']['Row'];
export type Conversation = Database['public']['Tables']['conversations']['Row'];
export type ConversationParticipant = Database['public']['Tables']['conversation_participants']['Row'];
export type Message = Database['public']['Tables']['messages']['Row'];
export type Notification = Database['public']['Tables']['notifications']['Row'];
export type Rating = Database['public']['Tables']['ratings']['Row'];

